"""

Revision ID: 08397c400520
Revises: 4d752a4782a2
Create Date: 2017-05-22 08:06:06.965196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08397c400520'
down_revision = '4d752a4782a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
