"""

Revision ID: 2fcbb8a6de94
Revises: 6126f3c188f2
Create Date: 2017-05-23 00:46:11.220811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcbb8a6de94'
down_revision = '6126f3c188f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
