"""

Revision ID: 4d752a4782a2
Revises: 2d58fc037930
Create Date: 2017-05-22 07:40:27.303359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d752a4782a2'
down_revision = '2d58fc037930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
