"""

Revision ID: 6126f3c188f2
Revises: 962aed476e64
Create Date: 2017-05-22 19:27:18.562698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6126f3c188f2'
down_revision = '962aed476e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
