"""

Revision ID: 667a1252c695
Revises: f4ca0645c0f1
Create Date: 2017-05-22 13:01:56.063460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667a1252c695'
down_revision = 'f4ca0645c0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
