"""

Revision ID: 7d3d765a09d2
Revises: 08397c400520
Create Date: 2017-05-22 08:10:59.169002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3d765a09d2'
down_revision = '08397c400520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_topic_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_topic_table',
    sa.Column('place_id', sa.VARCHAR(), nullable=True),
    sa.Column('topic_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['Place.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['Topic.id'], )
    )
    # ### end Alembic commands ###
