"""

Revision ID: 80fe8ef3a5ad
Revises: 7d3d765a09d2
Create Date: 2017-05-22 08:13:26.175063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fe8ef3a5ad'
down_revision = '7d3d765a09d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Place', sa.Column('ptype', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Place', 'ptype')
    # ### end Alembic commands ###
