"""test migration with message

Revision ID: 9622bbedce65
Revises: 80fe8ef3a5ad
Create Date: 2017-05-22 08:30:39.265103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9622bbedce65'
down_revision = '80fe8ef3a5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
