"""

Revision ID: 962aed476e64
Revises: 667a1252c695
Create Date: 2017-05-22 14:13:46.315994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962aed476e64'
down_revision = '667a1252c695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
