"""

Revision ID: a4cc3c4c3979
Revises: 23184a5b4714
Create Date: 2017-05-29 17:14:11.118115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cc3c4c3979'
down_revision = '23184a5b4714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
