"""

Revision ID: f4ca0645c0f1
Revises: 9622bbedce65
Create Date: 2017-05-22 12:59:10.494224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ca0645c0f1'
down_revision = '9622bbedce65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
